/**
 * Ask-a-question sidebar for the privacy track.
 *
 * The disclosure story matters more than the feature: this tutor's entire
 * context is source that is already public in this repository. No build state,
 * no wallet, no score. The panel says so out loud, because a reader learning
 * about `disclose` deserves to be told what the page itself discloses.
 */

'use client';

import { useState } from 'react';
import { Sparkles, Send, Loader2 } from 'lucide-react';
import type { AiAnswer } from '@/lib/ai/types';

const SUGGESTIONS = [
  'What is the difference between ledger and witness?',
  'Why is the commitment blinded?',
  'What would break if disclose were not required?',
];

export function CompactTutor({ moduleId }: { moduleId: string }) {
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState<AiAnswer | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [pending, setPending] = useState(false);

  async function ask(text: string) {
    const trimmed = text.trim();
    if (trimmed.length < 3 || pending) return;
    setPending(true);
    setError(null);
    setAnswer(null);
    try {
      const res = await fetch('/api/ai/compact-tutor', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ question: trimmed, moduleId }),
      });
      const data = (await res.json()) as AiAnswer & { error?: string };
      if (!res.ok) setError(data.error ?? 'The assistant is unavailable.');
      else setAnswer(data);
    } catch {
      setError('The assistant could not be reached.');
    } finally {
      setPending(false);
    }
  }

  return (
    <section className="panel mt-10 p-5">
      <h2 className="flex items-center gap-2 text-lg font-semibold">
        <Sparkles className="h-5 w-5 text-primary" />
        Ask about this circuit
      </h2>
      <p className="mt-1 text-sm text-fg-muted">
        Answers are grounded in the circuit source quoted above — all of it already public in
        this repository. Nothing about your build, wallet or score is sent.
      </p>

      <form
        className="mt-4 flex gap-2"
        onSubmit={(e) => {
          e.preventDefault();
          void ask(question);
        }}
      >
        <label className="sr-only" htmlFor="tutor-question">
          Your question about the Compact circuit
        </label>
        <input
          id="tutor-question"
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          maxLength={600}
          placeholder="Why is the threshold public?"
          className="flex-1 rounded-md border border-border bg-bg px-3 py-2 text-sm"
        />
        <button type="submit" className="btn text-sm" disabled={pending || question.trim().length < 3}>
          {pending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Send className="h-4 w-4" />}
          Ask
        </button>
      </form>

      <ul className="mt-3 flex flex-wrap gap-2">
        {SUGGESTIONS.map((s) => (
          <li key={s}>
            <button
              type="button"
              className="badge text-[11px] transition-colors hover:border-primary/50"
              onClick={() => {
                setQuestion(s);
                void ask(s);
              }}
              disabled={pending}
            >
              {s}
            </button>
          </li>
        ))}
      </ul>

      {error && (
        <p className="mt-4 rounded-md border border-warn/30 bg-warn/10 px-3 py-2 text-sm text-fg-muted">
          {error}
        </p>
      )}

      {answer && (
        <div className="mt-4">
          <p className="whitespace-pre-line text-sm text-fg-muted">{answer.answer}</p>
          <p className="mt-3 text-[11px] text-fg-muted">
            Generated by <span className="font-mono">{answer.model}</span>. It can be wrong — the
            circuit source above is the authority, and the scoring engine, not this model, decides
            what a design scores.
          </p>
        </div>
      )}
    </section>
  );
}
